"""initial enterprise ehr schema

Revision ID: e96829ea9bb3
Revises: 
Create Date: 2026-07-28 00:42:31.042912
"""
from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa

revision: str = 'e96829ea9bb3'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None

def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('audit_event',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('event_id', sa.String(length=80), nullable=False),
    sa.Column('occurred_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('actor', sa.String(length=160), nullable=False),
    sa.Column('role', sa.String(length=120), nullable=False),
    sa.Column('action', sa.String(length=160), nullable=False),
    sa.Column('resource_type', sa.String(length=120), nullable=False),
    sa.Column('resource_id', sa.String(length=120), nullable=True),
    sa.Column('patient_mpi_id', sa.String(length=80), nullable=True),
    sa.Column('facility_code', sa.String(length=80), nullable=True),
    sa.Column('outcome', sa.String(length=40), nullable=False),
    sa.Column('details', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('event_id')
    )
    op.create_index(op.f('ix_audit_event_occurred_at'), 'audit_event', ['occurred_at'], unique=False)
    op.create_table('facility',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=80), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('facility_type', sa.String(length=120), nullable=False),
    sa.Column('relation', sa.String(length=160), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_facility_code'), 'facility', ['code'], unique=True)
    op.create_table('integration_event',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('integration_event_id', sa.String(length=80), nullable=False),
    sa.Column('system', sa.String(length=120), nullable=False),
    sa.Column('event_type', sa.String(length=120), nullable=False),
    sa.Column('resource_type', sa.String(length=120), nullable=False),
    sa.Column('resource_id', sa.String(length=120), nullable=False),
    sa.Column('status', sa.String(length=80), nullable=False),
    sa.Column('attempts', sa.Integer(), nullable=False),
    sa.Column('payload_json', sa.Text(), nullable=False),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('processed_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_integration_event_integration_event_id'), 'integration_event', ['integration_event_id'], unique=True)
    op.create_index(op.f('ix_integration_event_status'), 'integration_event', ['status'], unique=False)
    op.create_index(op.f('ix_integration_event_system'), 'integration_event', ['system'], unique=False)
    op.create_table('patient',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('mpi_id', sa.String(length=80), nullable=False),
    sa.Column('mrn', sa.String(length=80), nullable=False),
    sa.Column('first_name', sa.String(length=120), nullable=False),
    sa.Column('middle_name', sa.String(length=120), nullable=True),
    sa.Column('last_name', sa.String(length=120), nullable=False),
    sa.Column('date_of_birth', sa.Date(), nullable=True),
    sa.Column('sex', sa.String(length=40), nullable=False),
    sa.Column('phone', sa.String(length=80), nullable=True),
    sa.Column('nida_number', sa.String(length=120), nullable=True),
    sa.Column('address', sa.String(length=255), nullable=True),
    sa.Column('region', sa.String(length=120), nullable=True),
    sa.Column('district', sa.String(length=120), nullable=True),
    sa.Column('next_of_kin', sa.String(length=255), nullable=True),
    sa.Column('payer', sa.String(length=120), nullable=True),
    sa.Column('member_number', sa.String(length=120), nullable=True),
    sa.Column('allergies', sa.Text(), nullable=False),
    sa.Column('problems', sa.Text(), nullable=False),
    sa.Column('medications', sa.Text(), nullable=False),
    sa.Column('consent_status', sa.String(length=80), nullable=False),
    sa.Column('identity_status', sa.String(length=80), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_patient_mpi_id'), 'patient', ['mpi_id'], unique=True)
    op.create_index(op.f('ix_patient_mrn'), 'patient', ['mrn'], unique=False)
    op.create_index(op.f('ix_patient_nida_number'), 'patient', ['nida_number'], unique=False)
    op.create_table('user_account',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.String(length=80), nullable=False),
    sa.Column('username', sa.String(length=120), nullable=False),
    sa.Column('display_name', sa.String(length=180), nullable=False),
    sa.Column('role_code', sa.String(length=80), nullable=False),
    sa.Column('facility_code', sa.String(length=80), nullable=False),
    sa.Column('password_hash', sa.Text(), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('requires_mfa', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('last_login_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_account_role_code'), 'user_account', ['role_code'], unique=False)
    op.create_index(op.f('ix_user_account_user_id'), 'user_account', ['user_id'], unique=True)
    op.create_index(op.f('ix_user_account_username'), 'user_account', ['username'], unique=True)
    op.create_table('appointment',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('appointment_id', sa.String(length=80), nullable=False),
    sa.Column('patient_id', sa.Integer(), nullable=False),
    sa.Column('facility_id', sa.Integer(), nullable=False),
    sa.Column('service', sa.String(length=160), nullable=False),
    sa.Column('provider', sa.String(length=160), nullable=True),
    sa.Column('appointment_type', sa.String(length=80), nullable=False),
    sa.Column('scheduled_start', sa.DateTime(timezone=True), nullable=False),
    sa.Column('scheduled_end', sa.DateTime(timezone=True), nullable=False),
    sa.Column('status', sa.String(length=80), nullable=False),
    sa.Column('arrival_method', sa.String(length=80), nullable=True),
    sa.Column('referral_id', sa.String(length=80), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_by', sa.String(length=160), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['facility_id'], ['facility.id'], ),
    sa.ForeignKeyConstraint(['patient_id'], ['patient.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_appointment_appointment_id'), 'appointment', ['appointment_id'], unique=True)
    op.create_index(op.f('ix_appointment_facility_id'), 'appointment', ['facility_id'], unique=False)
    op.create_index(op.f('ix_appointment_patient_id'), 'appointment', ['patient_id'], unique=False)
    op.create_index(op.f('ix_appointment_scheduled_start'), 'appointment', ['scheduled_start'], unique=False)
    op.create_index(op.f('ix_appointment_service'), 'appointment', ['service'], unique=False)
    op.create_index(op.f('ix_appointment_status'), 'appointment', ['status'], unique=False)
    op.create_table('encounter',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('encounter_id', sa.String(length=80), nullable=False),
    sa.Column('patient_id', sa.Integer(), nullable=False),
    sa.Column('facility_id', sa.Integer(), nullable=False),
    sa.Column('encounter_type', sa.String(length=80), nullable=False),
    sa.Column('service', sa.String(length=160), nullable=False),
    sa.Column('status', sa.Enum('PRE_REGISTERED', 'ARRIVED', 'WAITING_REGISTRATION', 'REGISTERED', 'WAITING_TRIAGE', 'TRIAGED', 'READY_FOR_PROVIDER', 'ROOMED', 'IN_PROGRESS', 'WAITING_RESULTS', 'READY_FOR_DISCHARGE', 'DISCHARGED', 'TRANSFERRED', 'LEFT_WITHOUT_BEING_SEEN', name='encounterstatus'), nullable=False),
    sa.Column('acuity', sa.String(length=40), nullable=False),
    sa.Column('location', sa.String(length=160), nullable=False),
    sa.Column('room', sa.String(length=80), nullable=True),
    sa.Column('provider', sa.String(length=160), nullable=True),
    sa.Column('reason_for_visit', sa.Text(), nullable=True),
    sa.Column('arrival_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('triage_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('provider_start_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('discharge_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('discharge_disposition', sa.String(length=160), nullable=True),
    sa.Column('discharge_summary', sa.Text(), nullable=True),
    sa.Column('follow_up', sa.Text(), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['facility_id'], ['facility.id'], ),
    sa.ForeignKeyConstraint(['patient_id'], ['patient.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_encounter_encounter_id'), 'encounter', ['encounter_id'], unique=True)
    op.create_index(op.f('ix_encounter_facility_id'), 'encounter', ['facility_id'], unique=False)
    op.create_index(op.f('ix_encounter_patient_id'), 'encounter', ['patient_id'], unique=False)
    op.create_index(op.f('ix_encounter_status'), 'encounter', ['status'], unique=False)
    op.create_table('inventory_item',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('item_id', sa.String(length=80), nullable=False),
    sa.Column('facility_id', sa.Integer(), nullable=False),
    sa.Column('item_code', sa.String(length=80), nullable=False),
    sa.Column('item_name', sa.String(length=255), nullable=False),
    sa.Column('category', sa.String(length=120), nullable=False),
    sa.Column('unit', sa.String(length=80), nullable=False),
    sa.Column('on_hand', sa.Integer(), nullable=False),
    sa.Column('reorder_level', sa.Integer(), nullable=False),
    sa.Column('batch_number', sa.String(length=120), nullable=True),
    sa.Column('expiry_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('location', sa.String(length=160), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['facility_id'], ['facility.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_inventory_item_category'), 'inventory_item', ['category'], unique=False)
    op.create_index(op.f('ix_inventory_item_facility_id'), 'inventory_item', ['facility_id'], unique=False)
    op.create_index(op.f('ix_inventory_item_item_code'), 'inventory_item', ['item_code'], unique=False)
    op.create_index(op.f('ix_inventory_item_item_id'), 'inventory_item', ['item_id'], unique=True)
    op.create_table('portal_message',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('message_id', sa.String(length=80), nullable=False),
    sa.Column('patient_id', sa.Integer(), nullable=False),
    sa.Column('direction', sa.String(length=40), nullable=False),
    sa.Column('channel', sa.String(length=80), nullable=False),
    sa.Column('subject', sa.String(length=255), nullable=False),
    sa.Column('body', sa.Text(), nullable=False),
    sa.Column('status', sa.String(length=80), nullable=False),
    sa.Column('sender', sa.String(length=160), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['patient_id'], ['patient.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_portal_message_message_id'), 'portal_message', ['message_id'], unique=True)
    op.create_index(op.f('ix_portal_message_patient_id'), 'portal_message', ['patient_id'], unique=False)
    op.create_table('public_health_event',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('event_id', sa.String(length=80), nullable=False),
    sa.Column('patient_id', sa.Integer(), nullable=False),
    sa.Column('condition_code', sa.String(length=80), nullable=False),
    sa.Column('condition_name', sa.String(length=255), nullable=False),
    sa.Column('event_type', sa.String(length=80), nullable=False),
    sa.Column('status', sa.String(length=80), nullable=False),
    sa.Column('district', sa.String(length=120), nullable=True),
    sa.Column('region', sa.String(length=120), nullable=True),
    sa.Column('reported_to', sa.String(length=120), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('reported_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['patient_id'], ['patient.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_public_health_event_condition_code'), 'public_health_event', ['condition_code'], unique=False)
    op.create_index(op.f('ix_public_health_event_event_id'), 'public_health_event', ['event_id'], unique=True)
    op.create_index(op.f('ix_public_health_event_patient_id'), 'public_health_event', ['patient_id'], unique=False)
    op.create_index(op.f('ix_public_health_event_status'), 'public_health_event', ['status'], unique=False)
    op.create_table('quality_incident',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('incident_id', sa.String(length=80), nullable=False),
    sa.Column('facility_id', sa.Integer(), nullable=False),
    sa.Column('patient_id', sa.Integer(), nullable=True),
    sa.Column('category', sa.String(length=120), nullable=False),
    sa.Column('severity', sa.String(length=40), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('status', sa.String(length=80), nullable=False),
    sa.Column('owner', sa.String(length=160), nullable=True),
    sa.Column('reported_by', sa.String(length=160), nullable=False),
    sa.Column('reported_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('closed_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['facility_id'], ['facility.id'], ),
    sa.ForeignKeyConstraint(['patient_id'], ['patient.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_quality_incident_facility_id'), 'quality_incident', ['facility_id'], unique=False)
    op.create_index(op.f('ix_quality_incident_incident_id'), 'quality_incident', ['incident_id'], unique=True)
    op.create_index(op.f('ix_quality_incident_status'), 'quality_incident', ['status'], unique=False)
    op.create_table('referral',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('referral_id', sa.String(length=80), nullable=False),
    sa.Column('patient_id', sa.Integer(), nullable=False),
    sa.Column('source_facility_code', sa.String(length=80), nullable=False),
    sa.Column('destination_facility_code', sa.String(length=80), nullable=False),
    sa.Column('service', sa.String(length=160), nullable=False),
    sa.Column('priority', sa.String(length=40), nullable=False),
    sa.Column('reason', sa.Text(), nullable=False),
    sa.Column('status', sa.String(length=80), nullable=False),
    sa.Column('requested_by', sa.String(length=160), nullable=False),
    sa.Column('accepted_by', sa.String(length=160), nullable=True),
    sa.Column('appointment_id', sa.String(length=80), nullable=True),
    sa.Column('closure_summary', sa.Text(), nullable=True),
    sa.Column('requested_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['patient_id'], ['patient.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_referral_patient_id'), 'referral', ['patient_id'], unique=False)
    op.create_index(op.f('ix_referral_referral_id'), 'referral', ['referral_id'], unique=True)
    op.create_index(op.f('ix_referral_status'), 'referral', ['status'], unique=False)
    op.create_table('bed',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('bed_id', sa.String(length=80), nullable=False),
    sa.Column('facility_id', sa.Integer(), nullable=False),
    sa.Column('unit', sa.String(length=120), nullable=False),
    sa.Column('room', sa.String(length=80), nullable=False),
    sa.Column('bed_label', sa.String(length=80), nullable=False),
    sa.Column('bed_type', sa.String(length=80), nullable=False),
    sa.Column('status', sa.String(length=80), nullable=False),
    sa.Column('encounter_id', sa.Integer(), nullable=True),
    sa.Column('isolation', sa.String(length=120), nullable=True),
    sa.Column('assigned_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['encounter_id'], ['encounter.id'], ),
    sa.ForeignKeyConstraint(['facility_id'], ['facility.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_bed_bed_id'), 'bed', ['bed_id'], unique=True)
    op.create_index(op.f('ix_bed_encounter_id'), 'bed', ['encounter_id'], unique=False)
    op.create_index(op.f('ix_bed_facility_id'), 'bed', ['facility_id'], unique=False)
    op.create_index(op.f('ix_bed_status'), 'bed', ['status'], unique=False)
    op.create_index(op.f('ix_bed_unit'), 'bed', ['unit'], unique=False)
    op.create_table('charge',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('charge_id', sa.String(length=80), nullable=False),
    sa.Column('patient_id', sa.Integer(), nullable=False),
    sa.Column('encounter_id', sa.Integer(), nullable=False),
    sa.Column('service_code', sa.String(length=80), nullable=False),
    sa.Column('description', sa.String(length=255), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('unit_price', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('status', sa.String(length=80), nullable=False),
    sa.Column('payer', sa.String(length=120), nullable=True),
    sa.Column('posted_by', sa.String(length=160), nullable=False),
    sa.Column('posted_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['encounter_id'], ['encounter.id'], ),
    sa.ForeignKeyConstraint(['patient_id'], ['patient.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_charge_charge_id'), 'charge', ['charge_id'], unique=True)
    op.create_index(op.f('ix_charge_encounter_id'), 'charge', ['encounter_id'], unique=False)
    op.create_index(op.f('ix_charge_patient_id'), 'charge', ['patient_id'], unique=False)
    op.create_table('claim',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('claim_id', sa.String(length=80), nullable=False),
    sa.Column('patient_id', sa.Integer(), nullable=False),
    sa.Column('encounter_id', sa.Integer(), nullable=False),
    sa.Column('payer', sa.String(length=120), nullable=False),
    sa.Column('member_number', sa.String(length=120), nullable=True),
    sa.Column('amount', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('status', sa.String(length=80), nullable=False),
    sa.Column('authorization_number', sa.String(length=120), nullable=True),
    sa.Column('denial_code', sa.String(length=80), nullable=True),
    sa.Column('denial_reason', sa.Text(), nullable=True),
    sa.Column('submitted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['encounter_id'], ['encounter.id'], ),
    sa.ForeignKeyConstraint(['patient_id'], ['patient.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_claim_claim_id'), 'claim', ['claim_id'], unique=True)
    op.create_index(op.f('ix_claim_encounter_id'), 'claim', ['encounter_id'], unique=False)
    op.create_index(op.f('ix_claim_patient_id'), 'claim', ['patient_id'], unique=False)
    op.create_index(op.f('ix_claim_payer'), 'claim', ['payer'], unique=False)
    op.create_index(op.f('ix_claim_status'), 'claim', ['status'], unique=False)
    op.create_table('clinical_note',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('note_id', sa.String(length=80), nullable=False),
    sa.Column('patient_id', sa.Integer(), nullable=False),
    sa.Column('encounter_id', sa.Integer(), nullable=False),
    sa.Column('note_type', sa.String(length=120), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('status', sa.String(length=80), nullable=False),
    sa.Column('author', sa.String(length=160), nullable=False),
    sa.Column('service', sa.String(length=160), nullable=False),
    sa.Column('body', sa.Text(), nullable=False),
    sa.Column('cosign_required', sa.Boolean(), nullable=False),
    sa.Column('signed_by', sa.String(length=160), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('signed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('amended_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['encounter_id'], ['encounter.id'], ),
    sa.ForeignKeyConstraint(['patient_id'], ['patient.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_clinical_note_encounter_id'), 'clinical_note', ['encounter_id'], unique=False)
    op.create_index(op.f('ix_clinical_note_note_id'), 'clinical_note', ['note_id'], unique=True)
    op.create_index(op.f('ix_clinical_note_note_type'), 'clinical_note', ['note_type'], unique=False)
    op.create_index(op.f('ix_clinical_note_patient_id'), 'clinical_note', ['patient_id'], unique=False)
    op.create_index(op.f('ix_clinical_note_status'), 'clinical_note', ['status'], unique=False)
    op.create_table('clinical_order',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('order_id', sa.String(length=80), nullable=False),
    sa.Column('encounter_id', sa.Integer(), nullable=False),
    sa.Column('order_type', sa.String(length=80), nullable=False),
    sa.Column('order_name', sa.String(length=255), nullable=False),
    sa.Column('priority', sa.String(length=40), nullable=False),
    sa.Column('status', sa.String(length=80), nullable=False),
    sa.Column('indication', sa.Text(), nullable=True),
    sa.Column('ordered_by', sa.String(length=160), nullable=False),
    sa.Column('ordered_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['encounter_id'], ['encounter.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_clinical_order_encounter_id'), 'clinical_order', ['encounter_id'], unique=False)
    op.create_index(op.f('ix_clinical_order_order_id'), 'clinical_order', ['order_id'], unique=True)
    op.create_table('flowsheet',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('flowsheet_id', sa.String(length=80), nullable=False),
    sa.Column('patient_id', sa.Integer(), nullable=False),
    sa.Column('encounter_id', sa.Integer(), nullable=True),
    sa.Column('name', sa.String(length=180), nullable=False),
    sa.Column('template_code', sa.String(length=120), nullable=False),
    sa.Column('status', sa.Enum('DRAFT', 'RUNNING', 'PAUSED', 'STOPPED', name='flowsheetstatus'), nullable=False),
    sa.Column('cadence_minutes', sa.Integer(), nullable=False),
    sa.Column('parameters_json', sa.Text(), nullable=False),
    sa.Column('elapsed_seconds', sa.Integer(), nullable=False),
    sa.Column('active_since', sa.DateTime(timezone=True), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('stopped_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('owner', sa.String(length=160), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['encounter_id'], ['encounter.id'], ),
    sa.ForeignKeyConstraint(['patient_id'], ['patient.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_flowsheet_flowsheet_id'), 'flowsheet', ['flowsheet_id'], unique=True)
    op.create_index(op.f('ix_flowsheet_patient_id'), 'flowsheet', ['patient_id'], unique=False)
    op.create_table('inventory_transaction',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('transaction_id', sa.String(length=80), nullable=False),
    sa.Column('inventory_item_id', sa.Integer(), nullable=False),
    sa.Column('transaction_type', sa.String(length=80), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('reason', sa.String(length=255), nullable=False),
    sa.Column('reference', sa.String(length=160), nullable=True),
    sa.Column('actor', sa.String(length=160), nullable=False),
    sa.Column('occurred_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['inventory_item_id'], ['inventory_item.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_inventory_transaction_inventory_item_id'), 'inventory_transaction', ['inventory_item_id'], unique=False)
    op.create_index(op.f('ix_inventory_transaction_transaction_id'), 'inventory_transaction', ['transaction_id'], unique=True)
    op.create_table('medication_order',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('medication_order_id', sa.String(length=80), nullable=False),
    sa.Column('patient_id', sa.Integer(), nullable=False),
    sa.Column('encounter_id', sa.Integer(), nullable=False),
    sa.Column('medication_name', sa.String(length=255), nullable=False),
    sa.Column('dose', sa.String(length=80), nullable=False),
    sa.Column('route', sa.String(length=80), nullable=False),
    sa.Column('frequency', sa.String(length=80), nullable=False),
    sa.Column('start_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('end_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('status', sa.String(length=80), nullable=False),
    sa.Column('indication', sa.Text(), nullable=True),
    sa.Column('ordered_by', sa.String(length=160), nullable=False),
    sa.Column('verified_by', sa.String(length=160), nullable=True),
    sa.Column('verified_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['encounter_id'], ['encounter.id'], ),
    sa.ForeignKeyConstraint(['patient_id'], ['patient.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_medication_order_encounter_id'), 'medication_order', ['encounter_id'], unique=False)
    op.create_index(op.f('ix_medication_order_medication_order_id'), 'medication_order', ['medication_order_id'], unique=True)
    op.create_index(op.f('ix_medication_order_patient_id'), 'medication_order', ['patient_id'], unique=False)
    op.create_index(op.f('ix_medication_order_status'), 'medication_order', ['status'], unique=False)
    op.create_table('module_activity',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('activity_id', sa.String(length=80), nullable=False),
    sa.Column('module_code', sa.String(length=80), nullable=False),
    sa.Column('patient_id', sa.Integer(), nullable=True),
    sa.Column('encounter_id', sa.Integer(), nullable=True),
    sa.Column('activity_type', sa.String(length=120), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('status', sa.String(length=80), nullable=False),
    sa.Column('priority', sa.String(length=40), nullable=False),
    sa.Column('assigned_to', sa.String(length=160), nullable=True),
    sa.Column('details', sa.Text(), nullable=True),
    sa.Column('payload_json', sa.Text(), nullable=False),
    sa.Column('created_by', sa.String(length=160), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['encounter_id'], ['encounter.id'], ),
    sa.ForeignKeyConstraint(['patient_id'], ['patient.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_module_activity_activity_id'), 'module_activity', ['activity_id'], unique=True)
    op.create_index(op.f('ix_module_activity_encounter_id'), 'module_activity', ['encounter_id'], unique=False)
    op.create_index(op.f('ix_module_activity_module_code'), 'module_activity', ['module_code'], unique=False)
    op.create_index(op.f('ix_module_activity_patient_id'), 'module_activity', ['patient_id'], unique=False)
    op.create_index(op.f('ix_module_activity_status'), 'module_activity', ['status'], unique=False)
    op.create_table('payment',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('payment_id', sa.String(length=80), nullable=False),
    sa.Column('patient_id', sa.Integer(), nullable=False),
    sa.Column('encounter_id', sa.Integer(), nullable=True),
    sa.Column('amount', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('method', sa.String(length=80), nullable=False),
    sa.Column('reference', sa.String(length=160), nullable=True),
    sa.Column('received_by', sa.String(length=160), nullable=False),
    sa.Column('received_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['encounter_id'], ['encounter.id'], ),
    sa.ForeignKeyConstraint(['patient_id'], ['patient.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_payment_patient_id'), 'payment', ['patient_id'], unique=False)
    op.create_index(op.f('ix_payment_payment_id'), 'payment', ['payment_id'], unique=True)
    op.create_table('work_item',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('work_item_id', sa.String(length=80), nullable=False),
    sa.Column('patient_id', sa.Integer(), nullable=True),
    sa.Column('encounter_id', sa.Integer(), nullable=True),
    sa.Column('queue', sa.String(length=120), nullable=False),
    sa.Column('task_type', sa.String(length=120), nullable=False),
    sa.Column('subject', sa.String(length=255), nullable=False),
    sa.Column('details', sa.Text(), nullable=True),
    sa.Column('priority', sa.String(length=40), nullable=False),
    sa.Column('status', sa.String(length=80), nullable=False),
    sa.Column('assigned_to', sa.String(length=160), nullable=True),
    sa.Column('due_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_by', sa.String(length=160), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['encounter_id'], ['encounter.id'], ),
    sa.ForeignKeyConstraint(['patient_id'], ['patient.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_work_item_encounter_id'), 'work_item', ['encounter_id'], unique=False)
    op.create_index(op.f('ix_work_item_patient_id'), 'work_item', ['patient_id'], unique=False)
    op.create_index(op.f('ix_work_item_queue'), 'work_item', ['queue'], unique=False)
    op.create_index(op.f('ix_work_item_status'), 'work_item', ['status'], unique=False)
    op.create_index(op.f('ix_work_item_work_item_id'), 'work_item', ['work_item_id'], unique=True)
    op.create_table('diagnostic_result',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('result_id', sa.String(length=80), nullable=False),
    sa.Column('order_id', sa.Integer(), nullable=True),
    sa.Column('patient_id', sa.Integer(), nullable=False),
    sa.Column('test_name', sa.String(length=255), nullable=False),
    sa.Column('value', sa.String(length=180), nullable=False),
    sa.Column('unit', sa.String(length=80), nullable=True),
    sa.Column('flag', sa.String(length=40), nullable=False),
    sa.Column('status', sa.String(length=80), nullable=False),
    sa.Column('source', sa.String(length=160), nullable=False),
    sa.Column('issued_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('acknowledged', sa.Boolean(), nullable=False),
    sa.Column('acknowledged_by', sa.String(length=160), nullable=True),
    sa.Column('acknowledged_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['order_id'], ['clinical_order.id'], ),
    sa.ForeignKeyConstraint(['patient_id'], ['patient.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_diagnostic_result_patient_id'), 'diagnostic_result', ['patient_id'], unique=False)
    op.create_index(op.f('ix_diagnostic_result_result_id'), 'diagnostic_result', ['result_id'], unique=True)
    op.create_table('flowsheet_event',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('flowsheet_id', sa.Integer(), nullable=False),
    sa.Column('action', sa.String(length=80), nullable=False),
    sa.Column('actor', sa.String(length=160), nullable=False),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('occurred_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['flowsheet_id'], ['flowsheet.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_flowsheet_event_flowsheet_id'), 'flowsheet_event', ['flowsheet_id'], unique=False)
    op.create_table('flowsheet_observation',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('flowsheet_id', sa.Integer(), nullable=False),
    sa.Column('parameter', sa.String(length=160), nullable=False),
    sa.Column('value', sa.String(length=160), nullable=False),
    sa.Column('unit', sa.String(length=80), nullable=True),
    sa.Column('source', sa.String(length=80), nullable=False),
    sa.Column('recorded_by', sa.String(length=160), nullable=False),
    sa.Column('recorded_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['flowsheet_id'], ['flowsheet.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_flowsheet_observation_flowsheet_id'), 'flowsheet_observation', ['flowsheet_id'], unique=False)
    op.create_table('medication_administration',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('administration_id', sa.String(length=80), nullable=False),
    sa.Column('medication_order_id', sa.Integer(), nullable=False),
    sa.Column('scheduled_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('action', sa.String(length=80), nullable=False),
    sa.Column('dose_given', sa.String(length=80), nullable=True),
    sa.Column('administered_by', sa.String(length=160), nullable=False),
    sa.Column('reason', sa.Text(), nullable=True),
    sa.Column('barcode_verified', sa.Boolean(), nullable=False),
    sa.Column('administered_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['medication_order_id'], ['medication_order.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_medication_administration_administration_id'), 'medication_administration', ['administration_id'], unique=True)
    op.create_index(op.f('ix_medication_administration_medication_order_id'), 'medication_administration', ['medication_order_id'], unique=False)
    # ### end Alembic commands ###

def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_medication_administration_medication_order_id'), table_name='medication_administration')
    op.drop_index(op.f('ix_medication_administration_administration_id'), table_name='medication_administration')
    op.drop_table('medication_administration')
    op.drop_index(op.f('ix_flowsheet_observation_flowsheet_id'), table_name='flowsheet_observation')
    op.drop_table('flowsheet_observation')
    op.drop_index(op.f('ix_flowsheet_event_flowsheet_id'), table_name='flowsheet_event')
    op.drop_table('flowsheet_event')
    op.drop_index(op.f('ix_diagnostic_result_result_id'), table_name='diagnostic_result')
    op.drop_index(op.f('ix_diagnostic_result_patient_id'), table_name='diagnostic_result')
    op.drop_table('diagnostic_result')
    op.drop_index(op.f('ix_work_item_work_item_id'), table_name='work_item')
    op.drop_index(op.f('ix_work_item_status'), table_name='work_item')
    op.drop_index(op.f('ix_work_item_queue'), table_name='work_item')
    op.drop_index(op.f('ix_work_item_patient_id'), table_name='work_item')
    op.drop_index(op.f('ix_work_item_encounter_id'), table_name='work_item')
    op.drop_table('work_item')
    op.drop_index(op.f('ix_payment_payment_id'), table_name='payment')
    op.drop_index(op.f('ix_payment_patient_id'), table_name='payment')
    op.drop_table('payment')
    op.drop_index(op.f('ix_module_activity_status'), table_name='module_activity')
    op.drop_index(op.f('ix_module_activity_patient_id'), table_name='module_activity')
    op.drop_index(op.f('ix_module_activity_module_code'), table_name='module_activity')
    op.drop_index(op.f('ix_module_activity_encounter_id'), table_name='module_activity')
    op.drop_index(op.f('ix_module_activity_activity_id'), table_name='module_activity')
    op.drop_table('module_activity')
    op.drop_index(op.f('ix_medication_order_status'), table_name='medication_order')
    op.drop_index(op.f('ix_medication_order_patient_id'), table_name='medication_order')
    op.drop_index(op.f('ix_medication_order_medication_order_id'), table_name='medication_order')
    op.drop_index(op.f('ix_medication_order_encounter_id'), table_name='medication_order')
    op.drop_table('medication_order')
    op.drop_index(op.f('ix_inventory_transaction_transaction_id'), table_name='inventory_transaction')
    op.drop_index(op.f('ix_inventory_transaction_inventory_item_id'), table_name='inventory_transaction')
    op.drop_table('inventory_transaction')
    op.drop_index(op.f('ix_flowsheet_patient_id'), table_name='flowsheet')
    op.drop_index(op.f('ix_flowsheet_flowsheet_id'), table_name='flowsheet')
    op.drop_table('flowsheet')
    op.drop_index(op.f('ix_clinical_order_order_id'), table_name='clinical_order')
    op.drop_index(op.f('ix_clinical_order_encounter_id'), table_name='clinical_order')
    op.drop_table('clinical_order')
    op.drop_index(op.f('ix_clinical_note_status'), table_name='clinical_note')
    op.drop_index(op.f('ix_clinical_note_patient_id'), table_name='clinical_note')
    op.drop_index(op.f('ix_clinical_note_note_type'), table_name='clinical_note')
    op.drop_index(op.f('ix_clinical_note_note_id'), table_name='clinical_note')
    op.drop_index(op.f('ix_clinical_note_encounter_id'), table_name='clinical_note')
    op.drop_table('clinical_note')
    op.drop_index(op.f('ix_claim_status'), table_name='claim')
    op.drop_index(op.f('ix_claim_payer'), table_name='claim')
    op.drop_index(op.f('ix_claim_patient_id'), table_name='claim')
    op.drop_index(op.f('ix_claim_encounter_id'), table_name='claim')
    op.drop_index(op.f('ix_claim_claim_id'), table_name='claim')
    op.drop_table('claim')
    op.drop_index(op.f('ix_charge_patient_id'), table_name='charge')
    op.drop_index(op.f('ix_charge_encounter_id'), table_name='charge')
    op.drop_index(op.f('ix_charge_charge_id'), table_name='charge')
    op.drop_table('charge')
    op.drop_index(op.f('ix_bed_unit'), table_name='bed')
    op.drop_index(op.f('ix_bed_status'), table_name='bed')
    op.drop_index(op.f('ix_bed_facility_id'), table_name='bed')
    op.drop_index(op.f('ix_bed_encounter_id'), table_name='bed')
    op.drop_index(op.f('ix_bed_bed_id'), table_name='bed')
    op.drop_table('bed')
    op.drop_index(op.f('ix_referral_status'), table_name='referral')
    op.drop_index(op.f('ix_referral_referral_id'), table_name='referral')
    op.drop_index(op.f('ix_referral_patient_id'), table_name='referral')
    op.drop_table('referral')
    op.drop_index(op.f('ix_quality_incident_status'), table_name='quality_incident')
    op.drop_index(op.f('ix_quality_incident_incident_id'), table_name='quality_incident')
    op.drop_index(op.f('ix_quality_incident_facility_id'), table_name='quality_incident')
    op.drop_table('quality_incident')
    op.drop_index(op.f('ix_public_health_event_status'), table_name='public_health_event')
    op.drop_index(op.f('ix_public_health_event_patient_id'), table_name='public_health_event')
    op.drop_index(op.f('ix_public_health_event_event_id'), table_name='public_health_event')
    op.drop_index(op.f('ix_public_health_event_condition_code'), table_name='public_health_event')
    op.drop_table('public_health_event')
    op.drop_index(op.f('ix_portal_message_patient_id'), table_name='portal_message')
    op.drop_index(op.f('ix_portal_message_message_id'), table_name='portal_message')
    op.drop_table('portal_message')
    op.drop_index(op.f('ix_inventory_item_item_id'), table_name='inventory_item')
    op.drop_index(op.f('ix_inventory_item_item_code'), table_name='inventory_item')
    op.drop_index(op.f('ix_inventory_item_facility_id'), table_name='inventory_item')
    op.drop_index(op.f('ix_inventory_item_category'), table_name='inventory_item')
    op.drop_table('inventory_item')
    op.drop_index(op.f('ix_encounter_status'), table_name='encounter')
    op.drop_index(op.f('ix_encounter_patient_id'), table_name='encounter')
    op.drop_index(op.f('ix_encounter_facility_id'), table_name='encounter')
    op.drop_index(op.f('ix_encounter_encounter_id'), table_name='encounter')
    op.drop_table('encounter')
    op.drop_index(op.f('ix_appointment_status'), table_name='appointment')
    op.drop_index(op.f('ix_appointment_service'), table_name='appointment')
    op.drop_index(op.f('ix_appointment_scheduled_start'), table_name='appointment')
    op.drop_index(op.f('ix_appointment_patient_id'), table_name='appointment')
    op.drop_index(op.f('ix_appointment_facility_id'), table_name='appointment')
    op.drop_index(op.f('ix_appointment_appointment_id'), table_name='appointment')
    op.drop_table('appointment')
    op.drop_index(op.f('ix_user_account_username'), table_name='user_account')
    op.drop_index(op.f('ix_user_account_user_id'), table_name='user_account')
    op.drop_index(op.f('ix_user_account_role_code'), table_name='user_account')
    op.drop_table('user_account')
    op.drop_index(op.f('ix_patient_nida_number'), table_name='patient')
    op.drop_index(op.f('ix_patient_mrn'), table_name='patient')
    op.drop_index(op.f('ix_patient_mpi_id'), table_name='patient')
    op.drop_table('patient')
    op.drop_index(op.f('ix_integration_event_system'), table_name='integration_event')
    op.drop_index(op.f('ix_integration_event_status'), table_name='integration_event')
    op.drop_index(op.f('ix_integration_event_integration_event_id'), table_name='integration_event')
    op.drop_table('integration_event')
    op.drop_index(op.f('ix_facility_code'), table_name='facility')
    op.drop_table('facility')
    op.drop_index(op.f('ix_audit_event_occurred_at'), table_name='audit_event')
    op.drop_table('audit_event')
    # ### end Alembic commands ###
