"""add telehealth sessions

Revision ID: ec1dda2c4a2a
Revises: e96829ea9bb3
Create Date: 2026-07-28 00:53:24.234817
"""
from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa

revision: str = 'ec1dda2c4a2a'
down_revision: Union[str, None] = 'e96829ea9bb3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None

def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('telehealth_session',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('session_id', sa.String(length=80), nullable=False),
    sa.Column('patient_id', sa.Integer(), nullable=False),
    sa.Column('facility_id', sa.Integer(), nullable=False),
    sa.Column('appointment_id', sa.Integer(), nullable=True),
    sa.Column('encounter_id', sa.Integer(), nullable=True),
    sa.Column('service', sa.String(length=160), nullable=False),
    sa.Column('provider', sa.String(length=160), nullable=False),
    sa.Column('modality', sa.String(length=40), nullable=False),
    sa.Column('status', sa.String(length=80), nullable=False),
    sa.Column('reason', sa.Text(), nullable=True),
    sa.Column('scheduled_start', sa.DateTime(timezone=True), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('paused_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('ended_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('join_code', sa.String(length=80), nullable=False),
    sa.Column('created_by', sa.String(length=160), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['appointment_id'], ['appointment.id'], ),
    sa.ForeignKeyConstraint(['encounter_id'], ['encounter.id'], ),
    sa.ForeignKeyConstraint(['facility_id'], ['facility.id'], ),
    sa.ForeignKeyConstraint(['patient_id'], ['patient.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('join_code')
    )
    op.create_index(op.f('ix_telehealth_session_appointment_id'), 'telehealth_session', ['appointment_id'], unique=False)
    op.create_index(op.f('ix_telehealth_session_encounter_id'), 'telehealth_session', ['encounter_id'], unique=False)
    op.create_index(op.f('ix_telehealth_session_facility_id'), 'telehealth_session', ['facility_id'], unique=False)
    op.create_index(op.f('ix_telehealth_session_patient_id'), 'telehealth_session', ['patient_id'], unique=False)
    op.create_index(op.f('ix_telehealth_session_scheduled_start'), 'telehealth_session', ['scheduled_start'], unique=False)
    op.create_index(op.f('ix_telehealth_session_service'), 'telehealth_session', ['service'], unique=False)
    op.create_index(op.f('ix_telehealth_session_session_id'), 'telehealth_session', ['session_id'], unique=True)
    op.create_index(op.f('ix_telehealth_session_status'), 'telehealth_session', ['status'], unique=False)
    # ### end Alembic commands ###

def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_telehealth_session_status'), table_name='telehealth_session')
    op.drop_index(op.f('ix_telehealth_session_session_id'), table_name='telehealth_session')
    op.drop_index(op.f('ix_telehealth_session_service'), table_name='telehealth_session')
    op.drop_index(op.f('ix_telehealth_session_scheduled_start'), table_name='telehealth_session')
    op.drop_index(op.f('ix_telehealth_session_patient_id'), table_name='telehealth_session')
    op.drop_index(op.f('ix_telehealth_session_facility_id'), table_name='telehealth_session')
    op.drop_index(op.f('ix_telehealth_session_encounter_id'), table_name='telehealth_session')
    op.drop_index(op.f('ix_telehealth_session_appointment_id'), table_name='telehealth_session')
    op.drop_table('telehealth_session')
    # ### end Alembic commands ###
